# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9f45426c3ecf47d47d591342b5df125a31c6f0892855ce30a85d8ccc5b73e842d6c663d7a66e233ee82792dc5ceeb46c1e9d12b9edf546dcafe028920b85b14

test:
  secret_key_base: 151fa54d234201d8d0e5cd92a16245ef225fd1f2f3c1b3fb2d4e82eff11a177d40ccd25e0ea6941dbd85c20e88cadf286c48b6a293b80d23bc0fe847e937412b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
